/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bischemes.game;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

class GameRunnerTests {}
